package com.mvp.myeffecttools.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.mvp.myeffecttools.dao.LockApp;

import com.mvp.myeffecttools.dao.LockAppDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig lockAppDaoConfig;

    private final LockAppDao lockAppDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        lockAppDaoConfig = daoConfigMap.get(LockAppDao.class).clone();
        lockAppDaoConfig.initIdentityScope(type);

        lockAppDao = new LockAppDao(lockAppDaoConfig, this);

        registerDao(LockApp.class, lockAppDao);
    }
    
    public void clear() {
        lockAppDaoConfig.clearIdentityScope();
    }

    public LockAppDao getLockAppDao() {
        return lockAppDao;
    }

}
