package com.mvp.myeffecttools.dao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "LOCK_APP".
 */
@Entity
public class LockApp {

    @NotNull
    private String packageName;
    private boolean isProtece;

    @Generated
    public LockApp() {
    }

    @Generated
    public LockApp(String packageName, boolean isProtece) {
        this.packageName = packageName;
        this.isProtece = isProtece;
    }

    @NotNull
    public String getPackageName() {
        return packageName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPackageName(@NotNull String packageName) {
        this.packageName = packageName;
    }

    public boolean getIsProtece() {
        return isProtece;
    }

    public void setIsProtece(boolean isProtece) {
        this.isProtece = isProtece;
    }

}
