package com.mvp.myeffecttools.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "LOCK_APP".
*/
public class LockAppDao extends AbstractDao<LockApp, Void> {

    public static final String TABLENAME = "LOCK_APP";

    /**
     * Properties of entity LockApp.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property PackageName = new Property(0, String.class, "packageName", false, "PACKAGE_NAME");
        public final static Property IsProtece = new Property(1, boolean.class, "isProtece", false, "IS_PROTECE");
    }


    public LockAppDao(DaoConfig config) {
        super(config);
    }
    
    public LockAppDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"LOCK_APP\" (" + //
                "\"PACKAGE_NAME\" TEXT NOT NULL ," + // 0: packageName
                "\"IS_PROTECE\" INTEGER NOT NULL );"); // 1: isProtece
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"LOCK_APP\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, LockApp entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getPackageName());
        stmt.bindLong(2, entity.getIsProtece() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, LockApp entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getPackageName());
        stmt.bindLong(2, entity.getIsProtece() ? 1L: 0L);
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public LockApp readEntity(Cursor cursor, int offset) {
        LockApp entity = new LockApp( //
            cursor.getString(offset + 0), // packageName
            cursor.getShort(offset + 1) != 0 // isProtece
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, LockApp entity, int offset) {
        entity.setPackageName(cursor.getString(offset + 0));
        entity.setIsProtece(cursor.getShort(offset + 1) != 0);
     }
    
    @Override
    protected final Void updateKeyAfterInsert(LockApp entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(LockApp entity) {
        return null;
    }

    @Override
    public boolean hasKey(LockApp entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
